- hosts: server
  become: yes
  vars:
    project_dir: /home/ubuntu/SIH-MAIN
    repo_url: "https://github.com/visheshchoudhary/SIH-MAIN.git"
    repo_version: "main"

  tasks:
  
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Run docker compose
      shell: |
        cd {{ project_dir }}
        docker-compose up -d --build  
        
    - name: Install dependencies
      apt:
        name:
          - git
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: Install Docker Engine
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '755'

    - name: Clone project
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_dir }}"
        version: "{{ repo_version }}"
        force: yes

    - name: Run docker compose
      shell: |
        cd {{ project_dir }}
        docker-compose down || true
        docker-compose up -d --build
